### PR TITLE
Specify UTC time in Calendar widget

### PR DESCRIPTION
**Pull request by calumgunn**
Nails #58.

### CODE REVIEW

**Comment by bensymonds** [comment]
Ah ok I see, the `_zonecode` thing is saying it's UTC, so we just need to convert the time to that first. This makes sense to me, but I suppose let someone else check too.

**Comment by jgwhite** [comment]
I’m surprised that Add this event wants the time in that format rather than ISO8601. Is that a quirk of their service?

**Comment by bensymonds** [comment]
I think you have to create an account/log in to see any developer docs, so I couldn't be bothered to look. I agree it's a bit odd.

**Comment by jgwhite** [comment]
LGTM

**Comment by jgwhite** [comment]
Actually, @calumgunn one further suggestion — is there any sense in moving the utc conversion into the helper?

**Comment by calumgunn** [comment]
@jgwhite Yes, there is.

**Comment by jgwhite** [comment]
Eres un hombre muy juicioso.

**Comment by jgwhite** [comment]
:boom:

**Pull request merged**
